### PR TITLE
fix: Get PR author instead of commenter

### LINKED ISSUE #6: Action considers whoever sent the `!coauthor` command as the PR author
As shown here, when Sarah sent the command she was not included as a co-author, but the PR author was.
https://github.com/withastro/docs/pull/7009#issuecomment-1962962495

### PR DESCRIPTION
**Pull request by Fryuni**
Closes #6

### CODE REVIEW

File: src/index.ts [hunk 1]
```diff
@@ -17,12 +17,25 @@ async function run() {
 	const token = core.getInput("token", { required: true });
 	const octokit = github.getOctokit(token);
 	const pr = github.context.payload.issue?.number;
-	const author = github.context.payload.comment?.user.login;
```
Comment (kevinzunigacuellar) [inline src/index.ts:20]: I think it's possible to get the PR author from [`github.context.payload.issue.user.login`](https://github.com/kevinzunigacuellar/coauthor-action/actions/runs/7851702670/job/21429140494#step:3:151)

If that doesn't work, the graphql query also includes the [PR author](https://github.com/kevinzunigacuellar/coauthor-action/blob/main/src/constants.ts#L5-L7) so it's not necessary to make a second call.

**Review by kevinzunigacuellar — COMMENTED** [review]
Thanks for the quick PR! I think we might not need to make a second call to github to get the author. We could use the github context or the author in the graphql query.
